name: Request for subdomain
description: >-
  Use this issue form to request for a subdomain, even if you plan to write YAML
  files yourself later on
title: '[subdomain requests]: new subdomain - subdomain.<lorebooks|stellapent>.wiki'
body:
  - type: checkboxes
    id: legalese
    attributes:
      label: Legalese
      options:
        - label: >-
            I agree to the AUP and ToS of Community Lorebooks subdomain service
            as well as the code of conduct.
          required: true
        - label: >-
            I confirm that I will use my subdomain for personal or
            non-profit/non-commerical use only.
          required: true
  - type: textarea
    id: details
    attributes:
      label: Tell us about your project/organization
      description: >-
        A brief description should be enough, alongside contact details for
        administrative communications. If you need privacy, see the OWL string
        field below.
    validations:
      required: true
  - type: input
    id: subdomain_maintainer
    attributes:
      label: Who will be the designated subdomain maintainer
      description: >-
        If it is going to be used as a team, please mention the lead maintainers
        here.
    validations:
      required: true
  - type: input
    id: owl
    attributes:
      label: OWL string
      description: >-
        See https://lorebooks.wiki/docs/reference/registry#owl-strings for
        details on its usage. Skip this if you are fine publicizing your contact
        details.
  - type: input
    id: repo_url
    attributes:
      label: Link to repo
      description: >-
        Link to your project's source code (or atleast its website) Skip this if
        you don't fork MediaWiki/CMS backend (or static site generator tool and
        theming) or just use upstream repo link.
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms Creator](https://issue-forms-creator.netlify.app)
