#!/usr/bin/env bash
# shellcheck disable=SC2014
set -xeo pipefail

ROOT_DIR=$(git rev-parse --show-toplevel)
DNS_PARTIALS_DIR="${ROOT_DIR}/dns/partials"
TEMPDIR=$(mktemp -p /tmp -d merged_zonefiles.XXXXXXXXXXXX)

# Merge every zonefile partial into one giant file first
echo "Generating merged YAML files"
for item in "$DNS_PARTIALS_DIR"/lorebooks.wiki/*.yml; do
    cat "$item" >> "$TEMPDIR/lorebooks.wiki.yaml"
    echo "" >> "$TEMPDIR/lorebooks.wiki.yaml"
done
for item in "$DNS_PARTIALS_DIR"/stellapent.wiki/*.yml; do
    cat "$item" >> "$TEMPDIR/stellapent.wiki.yaml"
    echo "" >> "$TEMPDIR/stellapent.wiki.yaml"
done

# Convert to JSON to remove comments before loading it up
# back into the main config
cat "${ROOT_DIR}/dns/header.yml" > "$ROOT_DIR/dns/lorebooks.wiki.yaml"
cat "${ROOT_DIR}/dns/header.yml" > "$ROOT_DIR/dns/stellapent.wiki.yaml"

echo "Removing comments"
yq eval 'del(.. | select(tag == "!!comment")) | sort_keys(.)' "$TEMPDIR/lorebooks.wiki.yaml" >> "${ROOT_DIR}/dns/lorebooks.wiki.yaml"
yq eval 'del(.. | select(tag == "!!comment")) | sort_keys(.)' "$TEMPDIR/stellapent.wiki.yaml" >> "$ROOT_DIR/dns/stellapent.wiki.yaml"

echo "Cleaning up"
rm -r "$TEMPDIR"
