# Meta DNS records for Community Lorebooks project itself
# Maintainers:
# - Andrei Jiroh Halili (@ajhalili2006, ajhalili2006@crew.recaptime.dev)

? ''
: octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: ALIAS
  value: lorebooks-wiki.pages.dev.
'*':
  octodns:
    cloudflare:
      auto-ttl: true
      comment: wildcard redirect via virtnet.bond VPS
      proxied: true
  ttl: 300
  type: AAAA
  value: 2a0f:85c1:8b5::7cc
'*.mkdocs':
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: CNAME
  value: lorebooks-wiki.github.io.
'*.templates':
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: CNAME
  value: lorebooks-wiki.github.io.
'*.zulip-archive':
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: CNAME
  value: lorebooks-wiki.github.io.
_acme-challenge.api:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: CNAME
  value: pending-id._acme.deno.dev.
_acme-challenge.badges.api:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: CNAME
  value: 0d738b3d8fe48dd612acd44d._acme.deno.dev.
_acme-challenge.deno.hello:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: CNAME
  value: 9a8dbd25e5f083266d95ed6d._acme.deno.dev.
_gh-lorebooks-wiki-o:
  octodns:
    cloudflare:
      comment: github org verification
  ttl: 300
  type: TXT
  value: dd65821f06
_gh-lorebooks-wiki-o.beta:
  octodns:
    cloudflare:
      comment: github org verification
  ttl: 300
  type: TXT
  value: 84bf35bbce
_github-pages-challenge-lorebooks-wiki:
  octodns:
    cloudflare:
      comment: github pages verification
  ttl: 300
  type: TXT
  value: 2a22effdf86f737bc1a90f9d9d9120
_github-pages-challenge-lorebooks-wiki.beta:
  octodns:
    cloudflare:
      comment: github pages verification
  ttl: 300
  type: TXT
  value: 51a8f0224e55eb49a0b968e85ba1d9
api:
- octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: A
  value: 34.120.54.55
- octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: AAAA
  value: '2600:1901:0:6d85::'
badges.api:
- octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: A
  value: 34.120.54.55
- octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: AAAA
  value: '2600:1901:0:6d85::'
cdn:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: CNAME
  value: link.storjshare.io.
home:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: CNAME
  value: lorebooks-wiki.pages.dev.
meta.cdn:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: CNAME
  value: link.storjshare.io.
txt-cdn:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: TXT
  values:
  - storj-access:jwvik3gmllcibuqruoq56dmyk44a
  - storj-root:lorebooks-wiki-cdn
  - storj-tls:true
txt-meta.cdn:
  octodns:
    cloudflare:
      comment: Managed by recaptime-dev
  ttl: 300
  type: TXT
  values:
  - storj-access:jwhphlawjl44d35irmfy32h2bzhq
  - storj-root:lorebooks-wiki-cdn/meta
  - storj-tls:true
www:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: true
  ttl: 300
  type: CNAME
  value: lorebooks-wiki.pages.dev.