name: octoDNS Deployments

on:
  push:
    branches: ["main"]
    paths:
      - dns/partials/**/*.yml
      - dns/*.yml
      - octodns-config.yml
      - .github/workflows/dns.yml
      - Pipfile*
  pull_request:
    branches: ["main"]
    paths:
      - dns/partials/**/*.yml
      - dns/*.yml
      - octodns-config.yml
      - .github/workflows/dns.yml
      - Pipfile*
  workflow_dispatch:

jobs:
  test:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Prepare dependencies
      run: |
        sudo apt-get update && sudo apt-get install --yes jq
        pip install --user pipenv
        pipenv install
        sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
        git config user.email "recaptimebot@gmail.com"
        git config user.name "Recap Time Bot"
      env:
        VERSION: v4.45.1
        BINARY: yq_linux_amd64
    - name: Merge YAML-based DNS zonefile partials
      run: |
        pipenv run merge-zonefiles
        ./script/update-merged-zonefiles
    - name: Dry-run DNS records deployment
      run: pipenv run dns-dryrun
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
  deploy:
    if: github.event_name != 'pull_request'
    needs: [test]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Wait a bit for any changes
        run: sleep 15
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Prepare dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes jq
          pip install --user pipenv
          pipenv install
          sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
        env:
          VERSION: v4.45.1
          BINARY: yq_linux_amd64
      - name: Merge YAML-based DNS zonefile partials
        run: pipenv run merge-zonefiles
      - name: Get job ID for Slack notifications
        uses: austenstone/job-id@v1
        id: job_id
      - name: Deploy
        run: ./script/deploybot-github
        env:
          SLACK_BOT_TOKEN_HACKCLUB: ${{ secrets.SLACK_BOT_TOKEN_HACKCLUB }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          WORKFLOW_JOB_LOGS: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/job/${{ steps.job_id.outputs.job-id }}
          JOB_ID: ${{ steps.job_id.outputs.job-id }}
